---
name: Ruby Gem

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install necessary gems
        run: |
          gem install rotp -v 5.1.0 --no-document

      - name: prepare credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}

      - name: build gem
        run: |
          gem build *.gemspec

      - name: generateotp
        run: echo "::set-env name=OTPTOKEN::$(rotp --secret ${GEM_HOST_OTP_SECRET})"
        env:
          GEM_HOST_OTP_SECRET: ${{secrets.RUBYGEMS_OTP_SECRET}}

      - name: publish
        run: |
          gem push *.gem --otp ${{ env.OTPTOKEN }}

